#include <iostream>

using namespace std;

class CVariables
{
    static const string S_ADD_CTABLE_ALT;
    static const string S_CHOOSE_ELEMENT;
    static const string S_CHOOSE_CELL;
    static const string S_ENTER_VALUE;
    static const string S_ENTER_NAME;
    static const string S_ENTER_TABLE_LENGTH;
    static const string S_DEFAULT;
    static const string S_PARAMETIC;
    static const string S_NAME;
    static const string S_AMOUNT_OF_CELL;
    static const string S_NO_COMMAND;
    static const string S_DEFAULT_MENU;
    static const string S_MENU1;
    static const string S_DELETE_MENU;
    static const string S_ENTER_COMMAND;
    static const string S_COMMAND;
    static const string S_EMPTY_COMMAND;
    static const string S_DELETE;
    static const string S_WITHOUT_PARAMETER;
    static const string S_COPY;
    static const string S_COPY_NAME;
    static const string S_SPACE;
    static const string S_LENGTH;
    static const string S_VALUE;
    static const string S_MINIMUM;
    static const string S_SUBMENU1;
    static const string S_SUBMENU1_COMMAND;
    static const string S_ADD_CTABLE;
    static const string S_ADD_CTABLE_COMMAND;
    static const string S_CHANGE_TABLE_LENGTH;
    static const string S_CHANGE_TABLE_LENGTH_COMMAND;
    static const string S_DELETE_CTABLE;
    static const string S_DELETE_CTABLE_COMMAND;
    static const string S_DELETE_ALL;
    static const string S_DELETE_ALL_COMMAND;
    static const string S_CHANGE_NAME;
    static const string S_CHANGE_NAME_COMMAND;
    static const string S_CLONE;
    static const string S_CLONE_COMMAND;
    static const string S_SET_VALUE;
    static const string S_SET_VALUE_COMMAND;
    static const string S_ALL_TABLES;
    static const string S_ALL_TABLES_COMMAND;
    static const string S_WRONG_NUMBER;
    static const string S_WRONG_ELEMENT;
    static const string S_EXIT;
    static const string S_SUBMENU2;
    static const string S_SUBMENU3;
    static const string S_SUBMENU2_COMMAND;
    static const string S_SUBMENU3_COMMAND;
    static const string S_BACK;
    static const string CHOOSE_ELEMENT;
    static const string CHOOSE_CELL;
    static const string ENTER_VALUE;
    static const string HELP;
};
